import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const battle = readFileSync(new URL("../game.js", import.meta.url), "utf8");
const ui = readFileSync(new URL("../src/ui.js", import.meta.url), "utf8");
const icons = readFileSync(new URL("../src/icons.js", import.meta.url), "utf8");
const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const calibrator = readFileSync(new URL("../puppet-calibrator.html", import.meta.url), "utf8");

assert.match(battle, /drawDuskPass\(g\)/, "El combate debe incluir el fondo del paso al atardecer");
assert.match(battle, /drawMistMarsh\(g\)/, "El combate debe incluir el fondo de la marisma");
assert.match(battle, /drawMoonShrine\(g\)/, "El combate debe incluir el fondo del santuario lunar");
assert.match(battle, /createTurnTimeline\(\)/, "El combate debe crear una barra de orden de acción");
assert.match(battle, /const HUD_THEMES = Object\.freeze/, "Los marcos de combate deben compartir un catálogo de temas");
assert.match(battle, /hud-theme-ancestral/, "El HUD debe cargar el tema Pergamino ancestral");
assert.match(battle, /hud-theme-lunar/, "El HUD debe cargar el tema Santuario lunar");
assert.match(battle, /registerHudThemeFrames\(\)/, "Los marcos de vida y chakra deben registrarse como subframes transparentes");
assert.match(battle, /applyHudTheme\(themeId\)/, "El tema debe poder cambiarse durante el combate");
assert.match(battle, /localStorage\.setItem\("hud-theme"/, "La elección del marco debe persistir");
assert.match(html, /select id="hud-theme"/, "Opciones debe permitir elegir el marco de combate");
assert.match(battle, /makeHudThemeControl\(480, 367\)/, "El menú de pausa debe permitir cambiar el marco durante el combate");
assert.match(battle, /RANK_LEVELS/, "El rango del HUD debe representarse mediante un nivel numérico escalable");
assert.match(battle, /const healthBarWidth = 370/, "La vida debe usar una anchura compacta que deje respirar el centro del HUD");
assert.match(battle, /healthBarWidth, 22, 0x38df87/, "La vida debe caber dentro del hueco ilustrado sin deformarlo");
assert.match(battle, /chakraBarWidth, 10, 0x2eaff4/, "El chakra debe conservar un perfil fino dentro de su marco");
assert.match(battle, /displayWidth \* \(theme\.health\.height \/ theme\.health\.width\)/, "El marco de vida debe respetar la proporción original de cada tema");
assert.match(ui, /createGeometryMask\(\)/, "El relleno debe recortarse antes de quedar cubierto por el marco ilustrado");
assert.match(battle, /barOffset: Object\.freeze/, "Cada marco debe declarar su compensación vertical de barras");
assert.match(battle, /playerRankStar = this\.add\.text\(110, 160/, "La estrella de rango debe quedar alineada a la izquierda");
assert.match(battle, /setFlipX\(index === 1\)/, "El marco enemigo debe mirar hacia fuera y no chocar con el del jugador");
assert.doesNotMatch(battle, /playerX \+ 32, 57, "VIDA"/, "El HUD no debe mostrar la etiqueta VIDA");
assert.doesNotMatch(battle, /playerX \+ 32, 80, "CHAKRA"/, "El HUD no debe mostrar la etiqueta CHAKRA");
assert.match(html, /Pergamino ancestral/, "El selector debe ofrecer Pergamino ancestral");
assert.match(html, /Santuario lunar/, "El selector debe ofrecer Santuario lunar");
assert.match(battle, /this\.turnReady/, "Las acciones deben depender de que el turno esté listo");
assert.match(battle, /resetTurnTimeline\(\)/, "Los marcadores deben regresar al terminar una ronda");
assert.match(battle, /class PauseScene extends Phaser\.Scene/, "Debe existir una escena de pausa independiente");
assert.match(battle, /makePauseAction\([^\n]+"ABANDONAR"/, "La pausa debe permitir abandonar la misión");
assert.match(battle, /index < 6/, "La barra debe conservar siempre seis espacios de acción");
assert.match(battle, /this\.actions\[index\] \|\| null/, "Los espacios sin técnica deben renderizarse vacíos");
assert.match(battle, /Array\.from\(\{ length: 4 \}/, "La barra debe reservar cuatro ranuras configurables entre las acciones fijas");
assert.match(battle, /\.\.\.techniqueSlots,[\s\S]*action-guard/, "Guardia debe permanecer siempre en la sexta posición");
assert.match(ui, /if \(!action\) \{[\s\S]*return \{ empty: true/, "Una acción ausente debe producir un espacio bloqueado");
assert.match(ui, /setDisplaySize\(54, 54\)/, "Los iconos de acción deben caber en la semirrueda compacta");
assert.equal(packageJson.dependencies["lucide-static"], "1.55.0", "Lucide debe permanecer fijado a una versión reproducible");
assert.match(icons, /export function loadUiIcons/, "La integración debe exponer un cargador reutilizable de iconos");
assert.match(icons, /export function createUiIcon/, "La integración debe exponer un constructor reutilizable para Phaser");
assert.doesNotMatch(battle, /createUiIcon\(this, "health"/, "El marco debe contener la vida sin una etiqueta o icono exterior");
assert.doesNotMatch(battle, /createUiIcon\(this, "chakra"/, "El marco debe contener el chakra sin una etiqueta o icono exterior");
assert.match(battle, /createUiIcon\(this, "speed"/, "Velocidad debe usar el icono de Lucide");
assert.match(ui, /createUiIcon\(scene, "lock"/, "Los espacios bloqueados deben usar el icono de Lucide");
assert.match(battle, /action-strike/, "El golpe básico debe cargar su propio icono");
assert.match(battle, /jutsu\.id === "strike" && this\.hero\.joints\?\.shoulderRight/, "Solo Golpe veloz debe activar el puñetazo articulado");
assert.match(battle, /preparePlayerPunch\(this, this\.hero\)/, "Golpe veloz debe preparar el brazo antes de avanzar");
assert.match(battle, /releasePlayerPunch\(this, this\.hero\)/, "Golpe veloz debe extender el brazo al atacar");
assert.match(battle, /recoverPlayerPunch\(this, this\.hero\)/, "El brazo debe regresar a la pose neutral después del golpe");
assert.match(battle, /const strikeX = this\.foe\.body\.x - 105/, "Golpe veloz debe acercarse casi hasta la posición X del rival");
assert.match(battle, /targets: this\.hero\.shadow, x: strikeX/, "La sombra debe acompañar al personaje durante Golpe veloz");
assert.match(battle, /class MissionTravelScene extends Phaser\.Scene/, "Las misiones deben comenzar con una transición por el bosque");
assert.match(battle, /startPlayerRunning\(this, runner\)/, "La transición debe animar al jugador corriendo");
assert.match(battle, /direction: "toVillage"/, "Volver a la aldea debe reproducir la carrera en sentido inverso");
assert.match(battle, /scene: \[MissionTravelScene, BattleScene, PauseScene\]/, "La transición debe ejecutarse antes del combate");
assert.doesNotMatch(battle, /targets: this\.hero\.targets, y: "-=4"/, "La respiración no debe hacer flotar al personaje completo");
assert.match(calibrator, /Laboratorio de animación/, "El calibrador debe incluir un laboratorio para aprobar clips");
assert.match(calibrator, /animationClipList\(\)/, "El laboratorio y el juego deben compartir el catálogo declarativo completo");
assert.match(calibrator, /playAnimationPreview/, "El laboratorio debe poder reproducir los clips sin alterar coordenadas");
assert.match(calibrator, /JOINT_PARENTS/, "La vista previa debe respetar la jerarquía de articulaciones");
assert.match(calibrator, /applyAnimationPose/, "El laboratorio debe calcular cada pose articulada por fotograma");
assert.match(calibrator, /sampleAnimationPose/, "El laboratorio y Phaser deben compartir el muestreador de clips");
assert.match(calibrator, /version: 2/, "El calibrador debe exportar la nomenclatura anatómica corregida");
assert.match(calibrator, /data\.version === 1/, "El calibrador debe migrar JSON anteriores sin perder coordenadas");
assert.match(battle, /startPlayerGuard\(this, this\.hero\)/, "Guardia debe adoptar la pose defensiva articulada");
assert.match(battle, /loseHealth\(this\.player, this\.hero/, "Los impactos enemigos deben pasar por la reacción centralizada");
assert.match(battle, /loseHealth\(this\.enemy, this\.foe/, "El rival debe reaccionar visualmente al recibir daño");
assert.match(battle, /loseHealth\(target, fighter/, "Toda pérdida de vida debe pasar por una operación centralizada");
assert.equal((battle.match(/\.hp = Math\.max\(0/g) || []).length, 1, "No debe haber reducciones de vida fuera de loseHealth");
assert.match(battle, /createUiIcon\(this, "healthLoss"/, "La pérdida de vida debe mostrar una gota roja junto al número");
assert.match(battle, /ratio > 0\.5[\s\S]*ratio > 0\.25/, "La barra de vida debe cambiar entre verde, amarillo y rojo");
assert.match(battle, /\[\.\.\.this\.foe\.targets, this\.foe\.shadow\]/, "La sombra enemiga debe desvanecerse junto con el cuerpo");
assert.match(battle, /this\.foe = createPlayerFighter\(this, 740, fighterY, this\.playerAppearance\(\), true\)/, "El rival de prueba debe reutilizar la marioneta modular del jugador y mirar hacia él");
assert.match(battle, /preparePlayerPunch\(this, this\.foe\)/, "El rival modular debe preparar el brazo antes de atacar");
assert.match(battle, /targets: this\.foe\.shadow, x: strikeX/, "La sombra del rival debe acompañar su avance de ataque");
assert.doesNotMatch(battle, /targets: this\.foe\.targets, y: "-=3"/, "El rival no debe flotar respecto de su sombra durante el reposo");
assert.match(battle, /startPlayerGuard\(this, this\.hero\)/, "La defensa debe estar conectada al combate real");
assert.match(battle, /target\.maxHp \* 0\.16/, "Los golpes fuertes deben distinguirse por el porcentaje de vida máxima");
assert.match(battle, /stopPlayerGuard\(this, this\.hero\)/, "La pose defensiva debe liberarse al consumir la guardia");
assert.match(battle, /action-guard/, "La guardia debe cargar su propio icono");
assert.match(battle, /Number\(event\.key\) - 1/, "Las acciones deben ofrecer atajos de teclado del 1 al 6");
assert.match(ui, /String\(index \+ 1\)/, "Cada acción debe mostrar su atajo numérico");
assert.match(ui, /const ACTION_POSITIONS = \[/, "Las acciones deben distribuirse sobre una semirrueda lateral");
assert.doesNotMatch(ui, /drawNamePlate|namePlate/, "La semirrueda no debe repetir nombres que ya aparecen en el tooltip");
assert.match(battle, /function drawCubicBezier\(/, "La guía debe dibujar su curva sin depender de métodos inexistentes de Graphics");
assert.match(battle, /drawCubicBezier\(rail, \{ x: -8, y: 112 \}/, "La semirrueda debe conservar la curva exterior");
assert.doesNotMatch(battle, /rail\.(?:cubicBezierTo|bezierCurveTo)/, "La semirrueda no debe invocar métodos inexistentes de Phaser Graphics");
assert.match(ui, /x \+ width \/ 2/, "Los valores de vida y chakra deben quedar en el centro horizontal de la barra");
assert.match(ui, /setOrigin\(0\.5\)/, "Los valores deben centrarse sobre ambos ejes dentro del relleno");
assert.match(ui, /setDepth\(40\)/, "La zona interactiva de las acciones debe quedar por encima del escenario");
assert.match(ui, /Adopta una postura defensiva/, "La guardia debe explicar su efecto dentro del tooltip");
assert.match(ui, /Prec\./, "Las estadísticas de acción deben tener etiquetas comprensibles");
assert.match(battle, /"VELOCIDAD"/, "La línea temporal inferior debe identificarse como velocidad");
assert.match(battle, /button\.tooltip\.layer\.setVisible\(true\)/, "Los detalles deben aparecer al pasar el cursor");
assert.match(battle, /this\.time\.delayedCall\(3200/, "Los detalles deben desaparecer aunque el cursor permanezca sobre la técnica");
assert.doesNotMatch(battle, /ORDEN DEL TURNO/, "La interfaz no debe recuperar la barra antigua de turnos");
assert.doesNotMatch(battle, /messagePlate/, "El combate no debe mostrar una banda de mensajes persistente");
assert.doesNotMatch(battle, /Ronda \$\{this\.round\}/, "El HUD no debe anunciar el número de ronda");
assert.match(battle, /setSealPrompt\(/, "Las instrucciones de sellos deben vivir dentro del minijuego y no en una banda de batalla");
assert.match(battle, /const fighterY = 372/, "Los combatientes deben quedar más cerca del suelo");
assert.doesNotMatch(battle, /heroAura/, "El aura decorativa permanente del jugador debe eliminarse");
assert.match(battle, /cssScale \* pixelRatio/, "El lienzo debe combinar la escala visible con el DPR del dispositivo");
assert.match(battle, /width: renderSize\.width/, "El framebuffer debe usar el tamaño físico medido del escenario");
assert.match(battle, /setZoom\(renderResolution\)/, "La cámara debe preservar las coordenadas lógicas al aumentar la resolución");
assert.doesNotMatch(battle, /battle-hud-overlay-v1\.png/, "El combate no debe cargar el overlay con tarjetas gigantes");
assert.match(battle, /function sharpenTextTree\(/, "El texto debe ajustarse recursivamente incluso dentro de contenedores");
assert.match(battle, /child\.setResolution\(resolution\)/, "El texto del combate debe rasterizarse a alta resolución");
assert.match(icons, /width: 128, height: 128/, "Los SVG deben rasterizarse con suficiente resolución antes de ampliarlos");
assert.match(battle, /this\.playerTurnMarker = this\.add\.circle\(TIMELINE_START, trackY, 17/, "El marcador del jugador debe quedar centrado verticalmente en la barra");
assert.match(battle, /\[375, 475, 575, 675, 775, 875\]/, "Los chevrones deben repartirse por toda la barra de velocidad");
assert.match(battle, /targets: \[this\.playerTurnMarker, this\.playerTurnLetter\], x: TIMELINE_END/, "El marcador del jugador debe recorrer la línea temporal");
assert.doesNotMatch(battle, /fontFamily: "Arial/, "El combate debe compartir las tipografías del metajuego");
assert.match(html, /assets\/vendor\/phaser-3\.90\.0\.min\.js/, "Phaser debe servirse localmente para evitar dependencias de terceros");
assert.match(html, /desktop\.css\?v=0\.44\.4/, "El CSS corregido debe invalidar la caché anterior");

console.log("Pruebas de interfaz de combate superadas.");
